### ISSUE TITLE
Proposal/Enhancement Nominal Diameter from PE as External Diameter instead of Internal Diameter

### ISSUE THREAD

**Issue by ponceta** [qwat/qwat-data-model#109]
I'm not a pipe expert (not yet), but Sébastien told me that we usually add the External diameter as Nominal diameter and displayname for PE as an exception.

![image](https://cloud.githubusercontent.com/assets/8614223/13676691/19be98ca-e6e7-11e5-95bd-cc3da41fea62.png)

I do not know if this is a **swiss custom rule from the SIA** or a **custom from Pully** but **IF NOT** it would be great to adapt the material tables. I can make a PR but I wanted to discuss it with you guys first.

**Comment by tudorbarascu** [comment]
@ponceta Take a look at https://github.com/qwat/qwat-data-model/blob/309bebc3a912f58b6b771d582b2ce648a6f33a02/value_lists/vl_pipe_material.sql as there are some comments there that may be helpful to you.

Nominal diameter means approximate interior diameter, and although it is close to the external diameter, they're surely not the same (or at least not in any standard I've looked at in E.U. and Swiss).
For PE pipes, even more as the PE pipes should be always referred to by their external diameter, and not the nominal diameter, which is a measure that's more encountered in steel based pipes.

As you can see, the image that you posted above respects this convention and I haven't found any clue in standards that it would be otherwise.

If you could provide some standards for PE pipes (Swiss or not) that would support what you proposed it would be very nice.

All the best!

**Comment by 3nids** [comment]
@ponceta I believed you mixed columns signification: `diameter_nominal` is as @tudorbarascu explained the approximate internal diameter while `diameter` is the usual name (how you call it). So you should rather use `diameter` / `_displayname`all the time for lableing and so on.

**Comment by ponceta** [comment]
I've discussed with many people and looked into the SIA norm. It's like @tudorbarascu commented it in the materials a naming convention which is specific for plastic tubes. Nominal diameter is not dependent from it.

Ty for the clarification.
