### ISSUE TITLE
Update current logic can't handle testing triggers on views

### ISSUE THREAD

**Issue by haubourg** [qwat/qwat-data-model#148]
@sylvainbeo worked on PR #147 and found limits to update system for view triggers. 

Views and functions are not handled by delta files, they are generated by the /ordinary_data/views/rewrite_views.sh. 
So triggers on views need to be applied after calling that scripts and can't be inside main delta_xx.sql file. We need a finalize_delta.sql file. 
Those triggers are then currently untested, and may be erased by rewrite_view.sh.

**Comment by haubourg** [comment]
@3nids  voilà une des raisons de mes soucis sur la pull request (y en avait d'autres). 
A discuter demain pour trouver une solution.

**Comment by sylvainbeo** [comment]
Few weeks ago, views were still generated before the deltas (when upgrading). This is no more the case, as we could not get views evolutions in the delta (because of fields orders).

Now, views are generated after the deltas. This is an issue if we have to release some specific triggers on some views...solution has to be found there.

**Comment by sylvainbeo** [comment]
In my the new branch postdelta, ive added the hability to execute POST delta files after the DB comparison. 

https://travis-ci.org/qwat/qwat-data-model/builds/195664911

Please have a look and give me your feedbacks.

**Comment by 3nids** [comment]
fine with me.

**Comment by haubourg** [comment]
fixed in a4500d44149aebb98e16c04f8371fd24f6d0e62e
