### ISSUE TITLE
Add network routing functions 

### ISSUE THREAD

**Issue by haubourg** [qwat/qwat-data-model#171]
A common need is to add ways to compute water flow routing functions using valves status that can provide answer to the following queries:

- Find upstream pipes  and valves involved for leaks
- Find subscribers concerned by a water shortage when closing valves

Routing should be done in Database so that other clients that qgis desktop can use that feature. 

Routing can be achieved using recursive queries or pg_routing extension. 

Routing implies a good network connectivity and thus editing be also be supported by views raising soft or hard errors, such as not connected pipes in a tolerance, duplicated nodes, invalid geometries, unwanted crossing alerts. 
 
See #195 for more advanced user specifications

**Comment by haubourg** [comment]
A proposal has been sent by Bogdan Vaduva, using pg routing:

[pgRouting, QWAT water flow.pdf](https://github.com/qwat/qwat-data-model/files/976224/pgRouting.QWAT.water.flow.pdf)

**Comment by haubourg** [comment]
@qwat/qwat-psc here is the proposal from  Bogdan Vaduva (Roumania) discussed in tuesday's PSC session

**Comment by haubourg** [comment]
@bogdanvaduva Hi Bogdan, I filed your proposal for routing in this issue for QWAT. Feel free to comment or maybe better file a pull request !

**Comment by bogdanvaduva** [comment]
@haubourg thanks for the interest in the subject.
Right now I am still working on the routing to see if I can add the upstream/downstream functionality. This is different from QGEP where all the network is flowing in one direction. I have a few things in my mind to test to see if it works. Once I've done more testing I will fill a pull request.

**Comment by sylvainbeo** [comment]
I had a look on the document. I've mde a few changes to the SQL code to match the lastest version of Qwat data model. The code works fine on the qwat-data-demo data.

[qwat_network_routing.txt](https://github.com/qwat/qwat-data-model/files/1039784/qwat_network_routing.txt)

**Comment by haubourg** [comment]
@qwat-psc : we decided that PSC users could propose specifications to go further on this task. Can someone take the task during summer and propose a draft?

**Comment by bogdanvaduva** [comment]
@haubourg may be I am asking a stupid question. What are PSC users? Probably I can write a draft on what I have done. Does it helps?

**Comment by haubourg** [comment]
H @bogdanvaduva , PSC users are listed here https://github.com/orgs/qwat/teams and we meet remotely once a month to discuss technical points and priorities.  

If you are willing to propose specifications for use cases, that would be very nice and would help going forward !

**Comment by haubourg** [comment]
@varrieta If you have some screenshots of others tools doing what you need for routing features, please paste it here !

**Comment by bogdanvaduva** [comment]
Hi guys, it's been a while since I wrote to you, but I was a little bit busy. When I wrote to you about networking functions I had a few things in my mind:
**1.** Be able to tell if the pipe network can allow a customer to have water (using the data from the model)
**2.** Be able to tell which valves had to be closed in order to be able to shut down the water for a customer
**3.** Be able to export data into EPANET

Since last time I wrote, I tested the idea and added the EPANET function (this one was updated with the work of @nliaudat - great job). 

To see EPANET in work have a look below : 
![epanet](https://user-images.githubusercontent.com/11473648/49992766-a47e1c80-ff8d-11e8-84f3-62dace844196.gif)

PS: @m-kuhn I had written something similar for qgep with SWMM5

![swmm](https://user-images.githubusercontent.com/11473648/49992908-03439600-ff8e-11e8-8195-4af080e55728.gif)

All the files for qwat are in my fork of qwat-data-model/system. I can make a pull request, but as I wrote in my PDF, postgresql database require pgrouting to be enabled.

Regards

**Comment by ponceta** [comment]
@bogdanvaduva Thanks for the illustrations, this looks very promising!

It would be nice to invite you to one of our PSC in 2019.

Actually we are very busy with getting QGEP in production, I suggest to invite you online on second semester of 2019.

Our users are actually clarifying their needs in terms of network analysis, this will be awesome to compare the needs and to make the best choices for QWAT (and potentially QGEP too).

**Comment by bogdanvaduva** [comment]
Hi @ponceta, I'll participate at your PSC (just let me know when) :)

**Comment by lbartoletti** [comment]
@ponceta is this question will be debated next weeks/PSC?
