### ISSUE TITLE
Trigger for materials

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qwat-data-model#21]
Good morning Denis,

I am currently working on a solution that eases the choosing of the pipe material and it would be great if you could throw some advice on it as it will probably have consequences on the ui.

As currently, when the user chooses the material of the pipe, he's confronted with a long list of materials
E.g. for PE of 63 external diameter he has at least 5 options at first count (for pn 8, 10, 16, 20, 25 etc.).
I think that in the form the user should only with presented with one option for the PE 63 diameter.

I created a trigger that fits the material according to the nominal pressure (for PE and PE80 materials):
 If the user chooses an id_material with PE63 for PN 10, but the pipe pn is 20 the trigger chooses the id_material for PE 63 for the correct pn, 20).
Thus, by reworking the UI (haven't done it yet, but I want to do it today) and presenting only one PE63 value to the user  (doesn't matter which PN) who can also choose the pipe PN in another combobox or textedit, the input of the material is much faster.
However, there are small caveats that I'm thinking of depending on how a unique PE 63 value will be presented to the user.
As one way of restricting the values would be to just set them as inactive and run the query with is_active = true. But we won't be able to fetch the values after the id_material is changed.
I am thinking of using 2 layers in the project pointing to the pipe_material table but they may be better solutions.
What do you think?

PS
Although I had planed to do a merge request with the whole solution proposed I can also do an early one with just the trigger if you want.

**Comment by 3nids** [comment]
Hi Tudor,

Yeah, it's a bit painful at the moment.

While thinking at it, I found another approach.

First, we create a view that return a unique combination of material / 
diameter (this will remove the PN).

So you choose first in the combo box.

Next you have a second combo box which is actually the real material id.
What you do, is that the choice of the first combo box will filter the 
list in the second one, and instead of displaying the full material 
name, you display only the PN.

I think we could create such widget directly in QGIS.
This widget could avoid using view. It could be a suite of combos.
You choose one field to filter per combo.

So, the config of the widget:
combo 1: unique of material name
combo 2: unique of diameter using filter material
combo 3: unique of PN using filter name + material

I will think a bit more, but this could be a nice approach.

(Thus, we should remove the pressure_nominal field.)

What do you think?

Denis

**Comment by tudorbarascu** [comment]
It sounds really nice and clean,
The widget would not make it into 2.8 LTS though, right?
Do you think my trigger is still needed? It can be used to be sure there are no id_material that have incorrect pn correspondence.

**Comment by 3nids** [comment]
Yes it won't make in 2.8.
A solution would be to provide the same widget in a plugin. Feasible.

Regarding the trigger, I am not sure.
Don't you think we should remove the pressure_nominale field???

**Comment by tudorbarascu** [comment]
We could remove it, yes,
I am thinking if removing it would strip us from an easy way of changing the PN when selecting multiple pipes (different material and diameter). A case where this would be needed would be when doing hydraulic scenarios.
If removing it would still allow us to easy change the pn for the pipes, then we should drop it for sure.

**Comment by 3nids** [comment]
I will ask for an offer for this widget and let you know.

**Comment by tudorbarascu** [comment]
Just realized we cannot drop the pressure_nominal for pipes, as we currently just have combinations with nominal pressure for PE and PE80. For acier, cuivre for example we don't have any combinations that relate to the pn. We could add missing combinations from the hat though...

**Comment by 3nids** [comment]
I think we should add these otherwise it's not consistent.
What do you think?

**Comment by tudorbarascu** [comment]
Yep, I think it's the best. I will do it. I'm currently searching standards that may help filling the values.

**Comment by tudorbarascu** [comment]
I am unable to find a trusty source for steel standards. The PVC standards are already in. I'm closing this issue.
