### ISSUE TITLE
Automatically add a vertex when adding an object on pipe

### ISSUE THREAD

**Issue by vpicavet** [qwat/qwat-data-model#88]
When adding a new object on a pipe (valve, other punctual element), a new node should be automatically created using a trigger.

**Comment by 3nids** [comment]
the node is already there (a valve is a node). The idea is to add a pipe vertex at the node position.
Hence, this should be a trigger on the node insert/move: if it intersects with a pipe add a vertex.

**Comment by mhugo** [comment]
@3nids Would you have a very simple test database with a sample network so that I can test ?

**Comment by 3nids** [comment]
not right now, maybe @tudorbarascu ?

**Comment by mhugo** [comment]
@3nids So the need here is to split a linestring (of a pipe) on a point given by the geometry of a node (valve, pump, tanks, etc.) ?
Is ST_Split acceptable (postgis 2 only) ?

Just to get the overall picture: why this feature ? is it because the newly inserted vertex could be moved in the future if the user wants to move the linked element ?

**Comment by 3nids** [comment]
No need to split, just to add a vertex at the position.
The thing is that it's more reliable if a node lies on a vertex rather than
on the segment.




Le lun. 25 janv. 2016 5:14 PM, Hugo Mercier <notifications@github.com> a
écrit :

**Comment by tudorbarascu** [comment]
The main purpose to automatically add a vertex on the pipe for corresponding water objects is to greatly improve editing and reduce the risk that pipe editing breaks topology as shown in production.
For instance, in the following gif there are two pipes, each one having valves on top. The one on top doesn't have vertexes on it and when a user pulls the right vertex of the pipe in order to prolong or change the direction of the pipe, he may easily break the topology (pipe leaving valves location).
I actually encountered this quite a lot for the editing users, especially when the object is not in the view-port and the problem cannot be seen visually.

The pipe down below is easily edited as it has vertexes and editing the pipe with the node tool doesn't break the topology.

![vertex](https://cloud.githubusercontent.com/assets/3179646/12563905/20db07ec-c3b5-11e5-811a-45e367796a70.gif)

Moreover, in my opinion snapping to vertex is better than snapping to segment.
Also, if I'm not mistaken, it's easier/safer to ensure topology checks when you take vertexes into consideration.

I'll try and make a simple example network in the following days if I can find the time.

**Comment by mhugo** [comment]
@tudorbarascu thanks for your rich explanation. That was my understanding, but thanks for the confirmation :)

But as @3nids pointed out, there is a problem with point / line intersection test which is rarely true due to the representation of decimal points (see http://boundlessgeo.com/2012/07/does-the-intersection-intersect/) So I guess we may want to add an optional tolerance

**Comment by tudorbarascu** [comment]
That's exactly why our work-flow in Romania is either one of:
- create the vertex on the pipe, and then snap the water object on it 
- create the water object, add the pipe vertex and snap it to the water object

From my point of view, a water object that's not exactly on a vertex should be considered outside the network topology.

Yes, an optional tolerance may be added but it should be quite small.
Also, I think that in principle it would be better if the pipe vertex should snap to the water object and not vice-versa as the water objects are the ones usually identified in the field.

**Comment by mhugo** [comment]
Ok, I noticed the current behaviour is to warn the user when a node is created outside of a pipe.
So I've added (see PR #90) a small code that follow the same behaviour when adding a vertex.
If some tolerance is needed (something like 10^-6) we could replace st_intersects by st_distance and so on
